### ISSUE TITLE
sauvegarder les logs dans des fichiers séparés et daté

### ISSUE THREAD

**Issue by MichelDaab** [IGNF/myria3d#25]
Tout d'abord, j'ai la sensation qu'on gère les logs de deux manières différentes, d'un côté on va avoir le "rich.tree" et de l'autre le "log_hyperparameters" qui semblent faire en gros deux fois la même chose, "logger" les paramètres de config mais par deux chemins différents.

Ensuite, il faudrait sans doute enregistrer ces valeurs dans des fichiers différents avec une date, pour pouvoir faire le suivi des résultats en fonction des paramètres d'entrée.

**Comment by CharlesGaydon** [comment]
Alors ce sont deux choses différentes : la librairie rich permet simplement de printer une config, tandis que log_hyperparameters les logs dans Comet directement, avec une date, etc. donc tout est bien conservé à un seul endroit.
