### ISSUE TITLE
optimisation des clone()

### ISSUE THREAD

**Issue by MichelDaab** [IGNF/myria3d#26]
Pour la fonction extract_subtile_from_tile_data : 
https://github.com/IGNF/myria3d/blob/3d32791035c3495ee36a06c10cda51d93a250256/myria3d/data/datamodule.py#L324

Le code est : 
        sub = data.clone()
        sub.pos = sub.pos[mask]
        sub.x = sub.x[mask]
        sub.y = sub.y[mask]

Cela me fait mal de cloner tous les data pour ne garder que la sous-tuile, cela multiplié par le nombre de tuile. Ne pourrait-on pas remplacer ce bloc de code par : 
sub = data[mask].clone() ?

Au passage, dans cette fonction x et y sont utilisés dans les noms de variables à la fois dans le sens des coordonnées (x, y) et dans le sens features/targets du deep learning, c'est peu de dire que cela complique la compréhension

**Comment by CharlesGaydon** [comment]
Corrigé avec https://github.com/IGNF/myria3d/pull/33
