### ISSUE TITLE
Hydra searchpath is outdated - is it still necessary?

### ISSUE THREAD

**Issue by CharlesGaydon** [IGNF/myria3d#60]
https://github.com/IGNF/myria3d/blob/4e94bc029d113d01e36c9872cbcb75f1ab4975a1/configs/config.yaml#L48
@MichelDaab Is it still necessary ? Can we get rid of this line?

**Comment by Yarroudh** [comment]
Hello,

I'm getting this error : 

"fit
Cannot find primary config 'configs/config.yaml'. Check that it's in your config search path.

Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file:///home/anass/myria3d/configs
        provider=hydra-colorlog, path=pkg://hydra_plugins.hydra_colorlog.conf
        provider=schema, path=structured://

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace."
