### ISSUE TITLE
Echec lors de l'analyse du LIDAR HD IGN

### ISSUE THREAD

**Issue by phardy-egis** [IGNF/myria3d#67]
Je rencontre des difficultés pour faire la classificaiton d'un LIDAR HD IGN.

Voici les jeux de données utilisés:
- .LAZ LIDAR HD IGN (région de Montpellier): https://wxs.ign.fr/c90xknypoz1flvgojchbphgt/telechargement/prepackage/LIDARHD_PACK_MQ_2021$LIDARHD_1-0_LAZ_MQ-0772_6279-2021/file/LIDARHD_1-0_LAZ_MQ-0772_6279-2021.7z
- BD ORTHOHR: Téléchargé pour le département 34 ici => http://files.opendatarchives.fr/professionnels.ign.fr/orthohr/
- BD ORTHOHR_IRC: Téléchargé pour le département 34 ici => http://files.opendatarchives.fr/professionnels.ign.fr/orthohr_irc/

Afin de colorizer le raster, j'ai utilisé 2 pipelines PDAL:

**1. Colorization RVB (depuis ORTHOHR)**

Voici le fichier `pipeline.json`:
```sh
{
    "pipeline": [
        "./input/Semis_2021_0772_6278_LA93_IGN69.laz",
        {
            "type": "filters.colorization",
            "raster": "./input/ORTHOHR.tif",
        },
        {
            "type": "filters.range",
            "limits": "Red[1:]"
        },
        {
            "type": "writers.las",
            "compression": "true",
            "minor_version": "2",
            "dataformat_id": "3",
            "filename": "./input/Semis_2021_0772_6278_LA93_IGN69_colorized.laz"
        }
    ]
}
```

**2. Colorization Infrarouge (depuis ORTHOHR IRC)**

Voici le fichier `pipeline.json`:
```sh
{
    "pipeline": [
        "./input/Semis_2021_0772_6278_LA93_IGN69_colorized.laz",
        {
            "type": "filters.colorization",
            "raster": "./input/ORTHOHR_IRC.tif",
            "dimensions": "Infrared:1:1.0"
        },
        {
            "type": "filters.range",
            "limits": "Infrared[1:]"
        },
        {
            "type": "writers.las",
            "compression": "true",
            "minor_version": "4",
            "dataformat_id": "8",
            "filename": "./input/Semis_2021_0772_6278_LA93_IGN69_colorized_IR.laz"
        }
    ]
}
```

3. Le traitement est finalement appliqué avec `predict`.

```sh
python -m myria3d.predict --config-path /model/ --config-name proto151_V2.0_epoch_100_Myria3DV3.1.0_predict_config_V3.2.0.yaml predict.src_las=/lidar/input/Semis_2021_0772_6278_LA93_IGN69_colorized_IR.laz predict.output_dir=/lidar/output predict.ckpt_path=/model/proto151_V2.0_epoch_100_Myria3DV3.1.0.ckpt predict.gpus=0 datamodule.batch_size=10 hydra.run.dir=/log/hydra
```

4. EN résultat, le LAZ en sortie n'a que des points "Non classifiés"

![image](https://user-images.githubusercontent.com/111574152/229177504-0aab1122-31c0-463d-b711-acc819b5715c.png)

![image](https://user-images.githubusercontent.com/111574152/229177467-b9bc050a-33ec-4401-8f2c-bbb0b26fd2d9.png)

Avez-vous une idée de l'étape manquante dans le traitement ? 

Merci.

**Comment by CharlesGaydon** [comment]
Bonjour @phardy-egis, ma première piste est la suivante : la prédiction du modèle d'IA est par défaut stockée dans le canal PredictedClassification (cf. [la documentation](https://ignf.github.io/myria3d/tutorials/make_predictions.html#output-dimensions)). Est-ce que ce canal que vous regardez ?
Par ailleurs, l'API préférée pour lancer l'inférence a légèrement changé, et votre commande peut être actualisée en suivant [celle-ci](https://ignf.github.io/myria3d/tutorials/make_predictions.html#run-inference-from-source).
```bash
python run.py task.task_name=predict ...
```

**Comment by CharlesGaydon** [comment]
@phardy-egis Du nouveau sur ce problème ? :)
