### ISSUE TITLE
Classification des toits plats

### ISSUE THREAD

**Issue by KlatbahII** [IGNF/myria3d#72]
Bonjour,
Félicitation pour ce framework qui fonctionne très bien et permet d'obtenir une bonne classification du LiDAR.  

Nous avons réussi à prédire des dalles de notre LiDAR avec Myria3D.  
Les résultats sont très bons, mais il y a un problème qui revient assez fréquemment :  
des points qui font partie d'un bâtiment avec un toit plat sont classifiés comme "SOL". Il s'agit souvent d'une forme ronde ou ovale au milieu du toit.  

J'avais vu une [issue #58](https://github.com/IGNF/myria3d/issues/58) où tu parlais de la possibilité d'augmenter la taille des "tiles" de 50mètres à 100mètres.  
Je voulais donc savoir s'il est possible de modifier des paramètres lorsque l'on prédit avec Myria3D afin d'essayer de régler ce problème.  

Voici un apercu des problèmes rencontrés:
![2](https://user-images.githubusercontent.com/98017942/234044552-a4c1300d-feef-4f9b-a5fd-195d6b69b9a1.jpg)
![3](https://user-images.githubusercontent.com/98017942/234044558-544df41a-1e36-41f3-a49a-cab0671a2c8d.jpg)

J'ai également installé `lidar-prod` afin d'essayer de régler ce problème. Est-ce que `lidar-prod` peut régler ce problème de classification des toits plats ? 
En effet, il est indiqué qu'il permet d'améliorer les résultats de la classification obtenus avec `myria3d`.  
Je n'ai pas réussi à accéder à la BD UNI via les paramètres de connexion que tu indiques. Ne vaudrait-il pas mieux que tu indiques un accès à la BD TOPO car la BD UNI n'est pas censée être publique ?

Notre LiDAR a une résolution de 20pts par m², est-ce que cela peut être la cause de la mauvaise classification des toits plats? Faut il entraîner un nouveau modèle ?

Merci pour ton travail qui est très intéressant et nous a permis de classifier efficacement notre LiDAR

**Comment by CharlesGaydon** [comment]
Bonjour @KlatbahII, 
Cette confusion "sol - larges toits plats" est un problème récurrent en segmentation sémantique de lidar aérien. On rencontre le problème sur le Lidar HD IGN (à 10 impulsions / m²) également.

> J'avais vu une https://github.com/IGNF/myria3d/issues/58 où tu parlais de la possibilité d'augmenter la taille des "tiles" de 50mètres à 100mètres.

**Ca me semble être la bonne première approche**. Surtout si ton intérêt est sur le bâti et pas sur les plus petits objets - en effet mon intuition est qu'augmenter la taille de la donnée réduira (très) légèrement la séparation des objets suite aux aléas des samplings dans RandLaNet. J'avais fait de tests qui montrait une (très) légère dégradation des IoU sur certaines classes, maius je n'étais pas allé à l'époque regarder les large bâtiments visuellement. 
**Mais ça pourrait augmenter le champs réceptif et le contexte. Si cela fonctionne, on pourra envisager de documenter cette configuration dans myria3d. Car ça nous intéressera aussi à l'IGN.** 🧁 

Concernant lidar-prod : l'outil peut servir à valider/réfuter les erreurs d'une première classification "rule based". Ca peut permettre d'identifier pour correction humaine les cas où les probas du modèle ne sont pas claires, mais il faut au préalable avoir trouvé ces bâtiments avec un autre algo donc... Pas évident.

Sur les changements à faire dans lidar-prod (BDUni/BDTopo), est-ce que tu peux ouvrir une [issue sur le repo lidar-prod](https://github.com/IGNF/lidar-prod/issues) directement, en linkant notre discussion ? Je passe progressivement la main sur la maintenance applicative, donc ce ne sera pas moi qui prendrai cette décision. Lidar-prod est un outil vraiment orienté vers la production IGN, mais la question se pose effectivement.

**Comment by KlatbahII** [comment]
Bonjour, merci de ta réponse.  
J'avais également observé ce problème avec d'autres framework de classification de LiDAR aérien(KPConv).  
Pour notre classification, les 2 classes qui nous intéressent le plus sont:
- Végétation
- Bâtiment

Du coup j'espère vraiment pouvoir réussir à régler ce problème de toits plats.

Par rapport à la partie "technique" pour la modification des paramètres,  
dans l'issue que j'ai lié tu parlais de reconstruire l'image Docker, dans mon cas de figure j'utilise un environnement conda.  
J'imagine que je peux donc modifier le fichier de [config](https://github.com/IGNF/myria3d/blob/main/trained_model_assets/proto151_V2.0_epoch_100_Myria3DV3.1.0_predict_config_V3.3.0.yaml)  :

Voici le fichier auquel je fais référence pour les lignes : `proto151_V2.0_epoch_100_Myria3DV3.1.0_predict_config_V3.3.0.yaml`
```bash
#ligne 112
subtile_width: 50
# Modifier à 100 pour avoir des "tuiles" de 100 mètres et essayer de diminuer le problème des toits plats
```

Voici ce que tu disais dans l'issue ou modifier la taille des tuiles était indiquée
```bash
Additionnaly, you will need to increase the aforementionned "point budget" to 4 * 40000 points to have a comparable density.
I think the most convenient way to change those parameters for you would be to use a configuration file (i.e. edit the default config) and 
either rebuild the docker image, or pass the config to the image with keywords --config-path=XXX and config-name=XXX (hydra style).
```

Dans le fichier config, j'ai trouvé plusieurs mention de cette valeur de 40000

```bash
# datamodule:
#   transforms:
#     preparations:
# train:
# ligne 44
        MaximumNumNodes:
          _target_: myria3d.pctl.transforms.transforms.MaximumNumNodes
          _args_:
          - 40000

# datamodule:
#   transforms:
#     preparations:
# eval:
# Ligne 67
        MaximumNumNodes:
          _target_: myria3d.pctl.transforms.transforms.MaximumNumNodes
          _args_:
          - 40000

# datamodule:
#   transforms:
#     preparations:
# predict:
# ligne 91
        MaximumNumNodes:
          _target_: myria3d.pctl.transforms.transforms.MaximumNumNodes
          _args_:
          - 40000
```

Donc j'imagine qu'il faut modifier la partie `predict`.  
Quelle valeur dois-je rentrer à la place de 40 000 ? 160 000(4 * 40 000)

Par rapport à `lidar-prod`, pour l'instant j'ai réussi à faire la première étape `apply_on_building`, et le résultat observé était la création de groupe parmi les points de bâtiments.  
Je voulais donc savoir si les autres tâches peuvent modifier la classification des bâtiments.  
Et pas de souci pour la création des issues sur le repo lidar-prod.  

Merci beaucoup de ta réponse rapide, et les résultats que l'on a obtenu avec Myria3D sont très satisfaisants

**Comment by CharlesGaydon** [comment]
C'est exactement ça ! La valeur 40000 est là pour des questions de mémoire, car on veut contrôler la taille total d'un batch de données pour éviter un crash. 160000 est la valeur cohérente car on multiplie par quatre la surface. Tu peux également mettre une valeur très haute pour garder *tous* les points en inférence.

Pour lidar-prod : les groupes créés correspondent au résultat de la partie [Building Identification](https://ignf.github.io/lidar-prod/background/production_process.html#b-3-building-identification). Les autres tâches peuvent modifier une classification **déjà existante** du bâti. On appelle ça les "candidats bâti" (le code de classification est paramétrable [dans la config ici](https://github.com/IGNF/lidar-prod/blob/9f45c4a4f015778fb99049ad0f22e269eddcc809/configs/data_format/default.yaml#L38)) Typiquement une classification basée sur des règles qui aurait détecté les surfaces planes, etc. Et qu'on veut améliorer/corriger avec le modèle d'IA.

> Merci beaucoup de ta réponse rapide, et les résultats que l'on a obtenu avec Myria3D sont très satisfaisants
Cheers 😄

**Comment by KlatbahII** [comment]
Merci pour ta réponse, 
j'ai pu tester en modifiant les variables dont on avait parlé : 

```bash
# subtile_width: 50
subtile_width: 100

# predict:
# ligne 91
MaximumNumNodes:
  _target_: myria3d.pctl.transforms.transforms.MaximumNumNodes
  _args_:
  # - 40000
  - 160000
```

En mettant ces paramètres, et en lancant la prédiction sur 2 sous-dalles, les zones de SOL dans les toits plats a diminué pour les très grand bâtiments, mais cela a impacté la classification précédente.

C'est sur cette dalle que les résultats sont le plus visible selon moi.  
La première image correspond à la dalle prédite avec les paramètres de base.  
![1_base](https://user-images.githubusercontent.com/98017942/234910097-a6fd1eca-01b8-4380-aaec-07abb232912b.png)  
La deuxième image correspond à la même dalle avec une taille de tuile de 100 mètres et une valeur de 160 000.
![1_160](https://user-images.githubusercontent.com/98017942/234910095-57cc97ea-fe57-40a9-89ea-dce4d30b052f.png)  

Il y a une amélioration même si le problème persiste avec des fausses valeurs de SOL dans les bâtiments à toit plats.  

Voici la 2ème sous-dalle que j'ai classifié.  
La 1ère image est avec les réglages de base, et la 2ème avec une taille de tuile de 100 mètres et une valeur de 160 000.
![2_base](https://user-images.githubusercontent.com/98017942/234910094-f7657def-4216-43bc-96f7-a1ae48a04226.png)  
![2_160](https://user-images.githubusercontent.com/98017942/234910088-70e51f54-24bb-4f5f-92bc-17a62ba68796.png)  

Dans la deuxième la taille des toits plats et plus petit et j'ai l'impression que cela impacte plus l'ancienne classification(avec les réglages de base).Il y a une amélioration, mais il y a toujours des problèmes.  

Par rapport à `lidar-prod`, est ce que des dalles LiDAR "brutes" prédites avec myria3D peuvent être envoyé dans lidar-prod afin d'en améliorer la classification ? Et si oui quelle est l'ordre des étapes à suivre ?   

Quand tu dis 

    Typiquement une classification basée sur des règles qui aurait détecté les surfaces planes, etc. Et qu'on veut 
    améliorer/corriger avec le modèle d'IA

Est ce que cela veut dire qu'il faudrait rajouter de **nouveaux Scalar Fields(dimensions)** avec ce type d'information ?
Parce que dans mes recherches précédentes, j'avais trouvé un algorithme qui permettait assez facilement et rapidement de **détecter des surfaces planes**. Si on l'utilise sur une sortie de myria3d en excluant la végétation(par exemple), je pense qu'il serait possible d'obtenir les surfaces planes(telles qu'on peut les obtenir avec un algorithme RANSAC par exemple).   

Pour résumer, j'espère qu'avec une dalle prédite avec myria3d il est possible d'aller jusqu'au bout du process de `lidar-prod` afin de voir les résultats que l'on peut obtenir, si cela est possible bien entendu.

Merci encore

**Comment by CharlesGaydon** [comment]
Très intéressant, merci pour ces retours d'expérience.
Dans le premier cas l'amélioration est nette. Dans la deuxième sous-dalle on voit des amélioration mais aussi une régression (bâtiment au milieu à droite). Mais dans l'ensemble on place en bâti plus de points, ce qui est positif.
Tu mentionnes :  
> mais cela a impacté la classification précédente.

Est-ce tu peux élaborer ?
____________
```
Typiquement une classification basée sur des règles qui aurait détecté les surfaces planes, etc. 
Et qu'on veut améliorer/corriger avec le modèle d'IA
```

En effet : Myria3D+lidar-prod **ne sont pas conçu pour fonctionner à deux seulement.** Il manque une troisième brique, qui doit avoir une bonne "régularité géométrique" (i.e. pas de trous dans les plans). Un algo de détection de large plans peut être une bonne option pour identifier les toits. Et ensuite Myria3D fournit des probas de bâti. Et enfin lidar-prod, pour chaque plan / composante connexe de points "candidats bâtis", va valider ou réfuter (ou dire qu'il ne sait pas) en utilisant les probas bâti de myria3d et la BDUni(/BDOrtho).
Lidar-prod attend un code "candidats bati" (dans ton cas : qui correspondrait aux grands plans de grands bâtiments) dans le canal Classification. Ce code est 202 par défaut, cf. [la configuration par défaut](https://ignf.github.io/lidar-prod/configs.html).

![image](https://user-images.githubusercontent.com/11660435/237062468-ec36c7da-5d7e-4cac-a71d-720f31993834.png)

**Comment by CharlesGaydon** [comment]
@KlatbahII : dans l'issue que tu mentionne j'avais oublié qu'un paramètre important est également à modifier, my bad ! Cela peut avoir un impact sur la qualité générale des résultats, pour les grands bâtiments comme pour les plus petits. Je te laisse regarder le commentaire en question : https://github.com/IGNF/myria3d/issues/58#issuecomment-1543573629

**Comment by KlatbahII** [comment]
Merci pour tes 2 réponses,

Quand je disais

> mais cela a impacté la classification précédente

Je parlais de la classification obtenue avant de modifier les paramètres `subtile_width` et `myria3d.pctl.transforms.transforms.MaximumNumNodes` de **40 000** à **160 000**.

## Test `NormalizePos.subtile_width=50`

J'ai pu tester le paramètre que tu mentionnes dans ta dernière réponse: `datamodule.transforms.normalizations.NormalizePos.subtile_width=50`.  
Afin de voir les différences j'ai utilisé 3 configurations différentes:
La configuration de base
  - `subtile_width` = 50
  - **40 000**
  - ![50_40k](https://github.com/IGNF/myria3d/assets/98017942/b7a86653-2641-4824-89d9-1601d5081ca2)

La configuration avec des sous-tuiles avec une largeur de **100 et 160 000 points**
  - `subtile_width` = 100
  - **160 000**
  - ![100_160k](https://github.com/IGNF/myria3d/assets/98017942/47b95469-9350-4cdf-885f-b302ea4e08c0)

La configuration précédente avec le nouveau paramètre que tu as mentionné
  - `subtile_width` = 100
  - **160 000**
  - `datamodule.transforms.normalizations.NormalizePos.subtile_width=50`
  - ![100_160k_normalize_50](https://github.com/IGNF/myria3d/assets/98017942/6d168478-97e6-4313-ab14-c28d6a438443)

Et malgré ces  configurations différentes, **il y a n'a pas de configuration qui améliore les résultats**.  
En effet, dans les essais avec une taille de tuile de 100 mètres, *les grands toits plats sont mieux classifiés*, mais c'est la classification des *bâtiments plus petits qui est "dégradée"* par rapport à des essais avec une taille de tuile de 50 mètres(réglagles de base).   
Le paramètre que tu mentionnais dans l'autre issue n'a pas arrangé les résultats.  

## Recherche création "Troisième brique"

Pour la **"3ème brique"** dont tu parlais 

>  une troisième brique, qui doit avoir une bonne "régularité géométrique" (i.e. pas de trous dans les plans). 
> Un algo de détection de large plans peut être une bonne option pour identifier les toits

J'ai commencé à chercher des solutions de mon côté, et il y a une dimension du LiDAR qui est au coeur des 2 pistes les plus prometteuses: **HeightAboveGround**.   

### Création Dimension HeightAbove Ground

Dans mon cas de figure, le LiDAR que j'utilise a une classification de base très sommaire:
- **SOL (2)**
- **SURSOL(1)** = non classifié

Cela me permet de générer un **raster MNT(Modèle Numérique de Terrain)** en utilisant uniquement les points du sol(2), et en interpolant les zones vides(sans points) avec PDAL.  
La fonctionnalité PDAL [filters.hag_dem](https://pdal.io/en/latest/stages/filters.hag_dem.html) permet d'obtenir la dimension **HeightAboveGround** en utilisant le raster MNT.  
Il est également possible d'utiliser seulement le LiDAR pour générer **HeightAboveGround** avec la fonctionnalité PDAL [filters.hag_nn](https://pdal.io/en/latest/stages/filters.hag_nn.html).Il faut cependant avoir des points avec une valeur de 2 dans la dimension Classification.  
Dans le cas du **LiDAR HD**, ou il me semble qu'il n'y a pas de classification *SOL-SURSOL*, il y a des outils permettant de réaliser cette classification:
- [PDAL : filters.csf](https://pdal.io/en/latest/stages/filters.csf.html#filters-csf) : les meilleurs résultats que j'ai obtenu
- [PDAL : ground/unclassified](https://pdal.io/en/latest/stages/filters.html#ground-unclassified) : Les autres possibilités
- J'ai testé avec le logiciel(propriétaire) *Trimble RealWorks*, et la classification SOL/Sursol est quasi parfaite et permet de pouvoir générer un MNT.  
- Données de l'IGN :  [ RGE ALTI](https://geoservices.ign.fr/actualites/2020-12-10-MNT-MNS), utiliser ce MNT pour calculer `HeightAboveGround` 

## 1ère piste : Détection de larges plans

Voici les résultats de l'algorithme dont je te parlais qui permet de détecter les plans des toits. 
Dans ces exemples, j'ai isolé des bâtiments afin que le rendu soit plus visible. 

|![toits_plats](https://github.com/IGNF/myria3d/assets/98017942/6468e67d-7d03-436e-ba91-266af11e3b3a)|
|:--:|
|*J'ai également testé avec des bâtiments avec de grands toits plats, et les plans sont bien déterminés*|


Je pense que cette détection des plans pourrait faire office de 3ème brique.  
J'ai pensé à une implémentation possible:
  - filtrer lidar prédit `myria3d` **SOL** et **Bâtiment** et **HeightAboveGround** > hauteur permettant de s'assurer qu'il ne s'agit pas de points du sol : 0.5 mètre ? 1 mètre ?
  - Filtrer les points voisins afin de s'assurer que ce point fait partie d'un plan détecté(**à creuser**)
-  Modifier la Dimension **Classification** avec une valeur de 202
   -  Afin que cela soit utilisé par `lidar-prod`, on serait dans le cas dont tu parlais sur l'issue de lidar-prod :  **"surclassifier" (faux positifs)**

Je n'ai pas encore testé cette possibilité, mais il me semble que cela pourrait être intéressant.  
De plus, cet algorithme n'a pas de problèmes pour les bâtiments de grande tailles avec un toit plat.  

## 2ème piste : Détection des points de sol avec une valeur élevée dans le Dimension `HeightAboveGound`

Malgré le fait qu'elle soit très simple,c'est cette piste qui m'a permis d'obtenir les meilleurs résultats et d'identifier assez facilement tout les points de bâtiments à toit plats classifiés en **SOL**.  
Je modifie les valeurs de la dimension `UserData` afin d'isoler les points dont la classification pose problème(toits plats).  
L'idée ici est d'assigner une valeur de 6 pour les points qui ont une valeur de 2 dans la dimension confidence et une valeur de HeightAboveGround supérieure à 3mètres
Voici les différentes étapes réalisées:
- Création de la Dimension `HeightAboveGround` en utilisant le MNT de la dalle avec la méthode PDAL `filters.hag_dem`
- `filters.assign` pour modifier la valeur de la dimension `UserData`
  - **`UserData = 6 where confidence == 2 && HeightAboveGround > 3`**

L'idée ici est de modifier la valeur d'`UserData` en 6.  
Cela me permet ensuite de modifier la dimension `confidence`, afin de reclasser ces points en bâti.(**cette étape est pour mon process vu que je n'ai pas réussi à faire fonctionner `lidar-prod`**).  

Voici les 4 dimensions utilisées dans ce process:
- `confidence`: sortie de myria3d
- `HeightAboveGround`: créé avec `filters.hag_dem`
- `UserData`: valeurs modifiées avec `filters.assign`
  - Les zones en blanc correspondent au points de SOL que je modifie en bâtiment
  - Les petites zones en "vert clair" correspondent à des points que je reclassifie en NonCLassifié(1)
- `Classification` : J'ai filtré:
  - confidence = 6 
  - UserData = 6(les points de sol que je reclassifie en bâti)
  - J'assigne à ces points la valeur 202 dont tu parlais dans ta dernière réponse
  
|![4_dimensions](https://github.com/IGNF/myria3d/assets/98017942/e7ce2de1-ee91-4f32-922b-657c0b060c90)|
|:--:|
|*confidence, HeightAboveGround, UserData, Classification(avec la valeur 202 )*|

J'ai ensuite essayé de lancer `lidar-prod` avec les candidats bâti à 202 et cela ne permet pas de régler les problèmes de toits plats.  
J'avais obtenu les mêmes résultats que précédemment, ou les toits plats ne sont pas "complétés" par lidar-prod.  
Du coup on va utiliser cette 2ème piste qui nous permet de régler ce problème.  
Si cela t'intéresse je pourrais te passer les JSON PDAL que j'utilise.  

Merci encore pour `myria3d` qui nous a permis d'obtenir de très bons résultats.

**Comment by CharlesGaydon** [comment]
Merci @KlatbahII d'avoir pris le temps de faire ce partage d'expérience détaillé. Ca a une valeur immense pour nous, et je suis ravi que Myria3D vous permettent d'obtenir des résultats satisfaisants ! 😃 

Je vais essayer de faire une synthèse dans ce message, que je peux mettre à jour en fonction de tes retours :

## Champs réceptif à 100mx100m
-  Elargir le champs réceptis de 50mx50m à 100mx100m passe par la modification de trois éléments : `datamodule.subtile_width=100`, budget de points passé de 40000 à 160000 (cf. [config](https://github.com/IGNF/myria3d/blob/a739e007aaa3408662086c3a9e98e8d36928a78b/configs/datamodule/transforms/preparations/points_budget.yaml#L91)), `datamodule.transforms.normalizations.NormalizePos.subtile_width=50`. Cette dernière modification est théoriquement logique mais n'a pas d'impact.
- En élargissant le champs réceptif, il y a amélioration sur les grands bâtiments et dégradation sur les petits. Ce n'est donc pas une bonne piste pour améliorer la classification des bâtiments dans leur globalité.

##  Correction ciblée des toit larges détectés en sol par Myria3D
- La piste retenue consiste à reclasser en bâti les points prédits sol par Myria3D mais situés à une _hauteur au sol_ >= 3m. 
- La _hauteur au sol_ de chaque point est calculée par un algorithme de PDAL ([filters.hag_dem](https://pdal.io/en/latest/stages/filters.hag_dem.html)), appliqué sur une classification sol/sursol obtenue également via PDAL ([PDAL : filters.csf](https://pdal.io/en/latest/stages/filters.csf.html#filters-csf)).

**Comment by CharlesGaydon** [comment]
Je vais essayer de faire une synthèse dans ce message, que je peux mettre à jour en fonction de tes retours :

## Champs réceptif à 100mx100m
-  Elargir le champs réceptis de 50mx50m à 100mx100m passe par la modification de trois éléments : `datamodule.subtile_width=100`, budget de points passé de 40000 à 160000 (cf. [config](https://github.com/IGNF/myria3d/blob/a739e007aaa3408662086c3a9e98e8d36928a78b/configs/datamodule/transforms/preparations/points_budget.yaml#L91)), `datamodule.transforms.normalizations.NormalizePos.subtile_width=50`. Cette dernière modification est théoriquement logique mais n'a pas d'impact.
- En élargissant le champs réceptif, il y a amélioration sur les grands bâtiments et dégradation sur les petits. Ce n'est donc pas une bonne piste pour améliorer la classification des bâtiments dans leur globalité.

##  Correction ciblée des toit larges détectés en sol par Myria3D
- La piste retenue consiste à reclasser en bâti les points prédits sol par Myria3D mais situés à une _hauteur au sol_ >= 3m. 
- La _hauteur au sol_ de chaque point est calculée par un algorithme de PDAL ([filters.hag_dem](https://pdal.io/en/latest/stages/filters.hag_dem.html)), appliqué sur une classification sol/sursol obtenue également via PDAL ([PDAL : filters.csf](https://pdal.io/en/latest/stages/filters.csf.html#filters-csf)).

**Comment by CharlesGaydon** [comment]
Sur une dernière note : 
> J'ai ensuite essayé de lancer lidar-prod avec les candidats bâti à 202 et cela ne permet pas de régler les problèmes de toits plats.
J'avais obtenu les mêmes résultats que précédemment, ou les toits plats ne sont pas "complétés" par lidar-prod.

Si les points "candidats bati" incluent l'ensemble des points des bâtiments larges, alors `lidar-prod` devrait être capable de les valider, ou a minima de les classer en "incertain". `lidar-prod` ne gère pas forcément parfaitement les "trous dans le bâti", mais on s'attend en tout cas à ce que les points candidats appartenant à la même composante connexe soient traités ensemble, donc ça me surprend que tu mentionnes des toits "non complétés".

**Comment by CharlesGaydon** [comment]
A nouveau, merci @KlatbahII pour ton travail de formalisation et de partage. Tes expérimentations sont très claires, et j'ai actualisé mon message de synthèse en conséquence. :)

L'approche me paraît bonne pour gérer les cas des bus/camions.

## Usage de lidar-prod

- Ton deuxième essai est la bonne méthode : tous les points candidats doivent être identifiés (code=202)
- Tu regardes la dimensions `Group`. En théorie c'est pourtant la dimension `**Classification**` qui devrait être modifiée par lidar-prod, avec des validation/réfutation/incertitudes. Dans ce cas précis, si tu inspecte la `Classification` en sortie de lidar-prod, je m'attends à ce que je le large bâtiment soit classés en "**incertain**", car il est sous une emprise de ton shapefile de bâti (BDTopo) MAIS les probas sont effectivement très basses.
- Ton image de `Group` (_L'affichage de la dimension Group_) est normale pour le premier essai : ce sont bien des groupes de points "suggérés" _car n'appartenant pas aux candidats bati_ (l'idée étant qu'une validation rapide mais manuelle est ensuite possible). Par contre je m'attend à ce que le canal `Group` soit différent pour ton deuxième essai.

Donc en conclusion : je m'attends à ce que le canal Classification du deuxième essai soit en fait pas mal du tout ! Mais pas de miracle non plus sur les grands batis : le mieux qu'on peut espérer considérant les probas faibles c'est qu'ils finissent en "bâti incertain" grâce à la BDTopo :)

**Comment by CharlesGaydon** [comment]
(Pour info: je regarde généralement les issues de Myria3D qui sont de mon ressort le jeudi matin.)

**Comment by KlatbahII** [comment]
Petit retour, en effet il fallait regarder dans la dimension `Classification`.  
En regardant les 2 dalles différentes je vois qu'il y a une grande différence entre les 2.  
Dans la dimension `Classification`, la valeur maximum est de 10 pour les 2 dalles.  

Par rapport à ce que tu disais:

> Donc en conclusion : je m'attends à ce que le canal Classification du deuxième essai soit en fait pas mal du tout ! Mais pas de miracle non plus sur les grands batis : le mieux qu'on peut espérer considérant les probas faibles c'est qu'ils finissent en "bâti 
incertain" grâce à la BDTopo :)

- **La classification du deuxième essai est vraiment bien**, les toits sont parfait dans la dimension Classification avec une valeur de 10
- Par rapport au bâti incertain, je n'ai pas bien compris quelle valeur correspondrait à cette catégorie

## 1er essai

Dans cette version ou je n'avais mis que les points des toits plats classifiés en sol, ils ont tous une valeur de 10 dans la dimension Classification 

|![conditions](https://github.com/IGNF/myria3d/assets/98017942/5d113460-3d9a-4f74-9431-39b51d70111f)  |
|:--:|
|*Affichage de la dimension Classification pour la dalle ou je n'ai mis que les points mal classifiés dans les toits plats*|

## 2ème essai

Comme tu l'avais annoncé, les résultats sont vraiment satisfaisants ici.  

|![myria_conditions](https://github.com/IGNF/myria3d/assets/98017942/08fdaad7-5b6e-424b-87c5-accac3c447c3) |
|:--:|
|*Affichage de la dimension Classification pour la dalle qui contient tout les "candidats bâti"*|

## Résumé

La version avec tout les candidats bâti a grandement amélioré les résultats.  
Cependant, je ne comprends pas le sens de la valeur 10 dans la dimension Classification pour les points que j'ai placé dans les "candidats bâti"(j'ai cette valeur dans les 2 dalles).  
A noter, il y a également des points avec des valeurs 1 et 2 dans la dimension Classification, qui semblent correspondre aux points NonClassifiés et du Sol

|![valeur_classification](https://github.com/IGNF/myria3d/assets/98017942/63f75f93-fbd3-4926-82d7-cfa36ce2d44a)|
|:--:|
|*Ici j'affiche la dalle avec tout les candidats bâti, dans l'autre dalle la valeur est également de 10*|

Le process de détection des toits plats avec ma pipeline PDAL et `lidar-prod` en suivant permet d'identifier quasiment tout les bâtiments.  
Il suffit de comparer avec les images des messages précédents pour constater la différence.  
Je pense que j'implémenterais donc `lidar-prod` dans mon process après les JSON pour corrections des points des toits plats et détection des fantômes.  

Merci encore

**Comment by CharlesGaydon** [comment]
Tant qu'on est sur le sujet des lectures/écritures : je remarque au passage tes fichiers ne sont pas en Lambert93. Actuellement, l'EPSG:2154 est codé en dur dans lidar-prod. Je suppose que ça peut poser soucis pour le croisement avec les shapefiles de bâti BD Topo.
cf. [get_pdal_reader](https://github.com/IGNF/lidar-prod/blob/9f45c4a4f015778fb99049ad0f22e269eddcc809/lidar_prod/tasks/utils.py#L65) :

```python
def get_pdal_reader(las_path: str) -> pdal.Reader.las:
    """Standard Reader which imposes Lamber 93 SRS.

    Args:
        las_path (str): input LAS path to read.

    Returns:
        pdal.Reader.las: reader to use in a pipeline.

    """
    return pdal.Reader.las(
        filename=las_path,
        nosrs=True,
        override_srs="EPSG:2154",
    )
```

**Comment by KlatbahII** [comment]
Par rapport au fichier .laz que l'on utilise, lorsque j'ai créé les points avec une valeur de 202 j'ai du le faire avec FME parce qu'avec PDAL cela ne fonctionnait pas.Il m'indiquait que la valeur était trop élevée et qu'il la modifiait en 1. Je pourrais retrouver le message d'erreur si cela t'intéresse.
  
Peut-être que ce problème à écrire ces valeurs élevées avec PDAL explique les problèmes d'écriture de 202 ou une valeur plus élevée(206 ou 208 dont tu parlais précédemment pas bâti/incertain).  
Pour revenir sur les résultats que j'avais obtenu, tout les points de "candidats bâti" avaient une valeur de 10.  

Je vais ré-essayer d'utiliser `lidar-prod` avec une dalle LiDAR en Lambert93(EPSG:2154).  
J'utiliserais également un shapefile en Lambert93(EPSG:2154).  

Par rapport aux options de gestions d'autres SRC, j'ai bien envie de voir la direction que vous allez prendre à ce sujet.  

Quand tu dis

> laspy d'un LAS non produit par l'IGN, pour lequel le canal Classification est lu en 5 bits (cf. le Header laspy du fichier, qui indique une valeur maximale de 31 pour ce canal).

Est ce que tu pourrais me mettre un petit bout de code, comment récupérer ces informations ? notamment le Header  laspy.
Afin de vérifier si le canal Classification de mon LiDAR a bien une valeur maximale de 31.

Je vais regarder de mon côté pour les valeurs de la dimension `Classification`, je pense que cela peut venir de la version du LiDAR.
Je te tiens au courant

**Comment by leavauchier** [comment]
Bonjour, 
concernant le problème d'encodage des grandes valeurs de classification, j'ai trouvé une piste dans la spécification du las 1.4 (https://www.asprs.org/wp-content/uploads/2019/07/LAS_1_4_r15.pdf)
Les valeurs que peut prendre la classification dépendent du _Point Data Record Format_ (`dataformat_id` dans PDAL) :
* pour les record formats de 1 à 5 seules les valeurs de 0 à 31 sont acceptées (cf. table 8) et les bits supplémentaires sont utilisés pour autre chose)
* pour les formats de 6 à 10 elles peuvent aller de 0 à 255 (cf table 17)

Le writer LAS de PDAL écrit par défaut en las 1.2 et dans le record format 3, je pense que c'est pour ça que ça n'a pas fonctionné avec PDAL, mais je pense qu'en choisissant un record format >= 6 ça devrait fonctionner

Pour vérfier quelle valeur est utilisée, ceci devrait marcher : `pdal info --metadata my_file.laz | grep dataformat_id`

**Comment by CharlesGaydon** [comment]
Ok, merci pour toutes ces infos, j'ai l'impression qu'on commence à converger vers une résolution !
@KlatbahII :
- Léa Vauchier t'a fourni les commande pour vérifier tes formats actuels.  Préciser minor_version=4 et dataformat_id=8 en sortie des processus devrait fonctionner (cf. [la doc pdal du writer de las](https://pdal.io/en/latest/stages/writers.las.html)).
[Si vraiment ça ne fonctionne pas il y a toujours l'option de ne jamais impliquer de valeurs au dessus de 31, en changeant [le code pour les candidats bati](https://github.com/IGNF/lidar-prod/blob/9f45c4a4f015778fb99049ad0f22e269eddcc809/configs/data_format/default.yaml#L38) et les [codes en sortie de lidar-prod](https://github.com/IGNF/lidar-prod/blob/9f45c4a4f015778fb99049ad0f22e269eddcc809/configs/data_format/default.yaml#LL48C54-L48C54). Mais ce n'est pas très satisfaisant comme solution.]
- Pour la question des SRC, les réflexions avancent. C'est top si tu as des données Lambert 93 pour l'instant. Si tu souhaites proposer une contribution ou indiquer ton besoin, tu peux le faire sous l'issue susmentionnée https://github.com/IGNF/lidar-prod/issues/88. La maintenance applicative de Myria3d est reprise par @leavauchier, et inclue ce sujet.

**Comment by CharlesGaydon** [comment]
Je ferme. N'hésite pas à rouvrir l'issue si besoin.
