### ISSUE TITLE
Classification des falaises (au milieu de zones de végétation)

### ISSUE THREAD

**Issue by didiersmets** [IGNF/myria3d#80]
Bonjour,

En évaluant les nuages de points classés récemment mis à disposition sur le site du projet LidarHD, j'ai observé qu'il 
semble y avoir un souci important de classification des zones de falaises, d'autant plus lorsque les zones moins pentues alentours sont couvertes de végétation. L'exemple ci-dessous sur la dalle 0933_6505 le montre clairement (la majeure partie de la falaise est classée comme de la végétation), mais le problème semble récurrent (observé sur toutes les dalles ouvertes dans les pré-alpes). La coloration du nuage par orthophoto est bien sûr de peu d'utilité (voire trompeuse) dans ces cas. 

Pensez-vous que cela soit rattrapable ou bien ces nuages sont-ils considérés comme le produit fini ? Pour comparaison, les nuages classés du Lidar Suisse ne présentent pas, ou dans une bien moindre mesure, ce défaut de classification.

D'avance merci,
Bien cordialement,
Didier Smets

![0933_6505](https://github.com/IGNF/myria3d/assets/80471745/65291c55-90d3-421e-beae-1f9129b462fb)

**Comment by leavauchier** [comment]
Bonjour, 

merci pour votre retour !

Actuellement la classification du LidarHD n'utilise pas seulement Myria3d. Elle utilise une combinaison de plusieurs méthodes, ce qui fait que les résultats de Myria3d ne sont pas utilisés partout.
Pour les sujets liés au projet LidarHD, je vous invite à poser votre question sur la communeauté Osmose du projet : https://geoservices.ign.fr/rejoindre-la-communaute-lidar-hd 

Par curiosité, est-ce que vous observez le même problème en utilisant myria3d sur ces données ?

**Comment by didiersmets** [comment]
Bonjour et merci pour votre réponse. Ce n'est pas la première fois que je lis cette indication "communauté Osmose" mais concrètement de quoi s'agit-il ? Sur la page web que vous indiquez je ne vois rien d'autre que le titre "Rejoindre la communauté Lidar HD" (en plus des bandeaux qui sont communs à toutes les pages sur Géoservices) ? J'ai déjà un compte sur Geoservices auquel je peux me connecter mais nulle-part je ne vois de "communauté" où poser ma question. Pourriez-vous m'aiguiller plus précisément s'il-vous-plaît ?

Concernant le rendu myria3d seul, je n'ai pas encore eu l'occasion de vraiment le tester (nécessité de modifier les fichiers lidar distrués par l'IGN car il manque plusieurs champs scalaires attendus par myria3d), mais je reviendrai vers vous lorsque ce sera le cas.

**Comment by leavauchier** [comment]
Apparemment il s'agit d'un problème de la page web qui met énormément de temps à se charger avec Firefox, mais ça semble ne pas poser problème sur Edge ou Chrome : cette page est sensée afficher un formulaire pour s'inscire sur la communauté Osmose.

Concernant Osmose, il s'agit d'un forum rassemblant tous les utilisateurs du LIDAR HD sur lequel on répond à toutes les questions en lien avec le programme LIDAR HD, on réalise des ateliers thématiques et on partage des informations.

**Comment by CharlesGaydon** [comment]
> Concernant le rendu myria3d seul, je n'ai pas encore eu l'occasion de vraiment le tester (nécessité de modifier les fichiers lidar distrués par l'IGN car il manque plusieurs champs scalaires attendus par myria3d), mais je reviendrai vers vous lorsque ce sera le cas.

Une réaction sur le besoin de canaux supplémentaire : je mentionne dans cette issue [un outil permettant la colorisation des nuages de points par orthoimages IGN](https://github.com/IGNF/myria3d/issues/75).
