### ISSUE TITLE
Configuration : cherche à affecter les gpu quand 'trainer.gpus' est spécifié même quand 'accelerator=cpu'

### ISSUE THREAD

**Issue by MichelDaab** [IGNF/myria3d#84]
Quand on demande un apprentissage sur CPU (trainer.accelerator=cpu), mais qu'il y a quand même des gpu demandés dans la config (trainer.gpus: 2) et que les gpus ne sont pas disponible, il refuse de se lancer en expliquant que les gpus ne sont pas là

**Comment by CharlesGaydon** [comment]
C'est la conséquence de différentes redondances dans l'API du Trainer de Pytorch-Lightning. C'est un problème qui avait été idenfié, et depuis mars 2022 le flag `gpus` est d'ailleurs déprécié (cf. [cette PR](https://github.com/Lightning-AI/pytorch-lightning/pull/11040)), et la manière par défaut d'utiliser des devices est de spécifier `trainer.devices=k trainer.accelerator=cpu/gpu`.

C'est un soucis sans grande conséquence autre que de la confusion pour nous actuellement...

Si on met à jour Pytorch et Pytorch-Lightning ça peut être l'occasion de s'adapter à cette nouvelle API. D'ailleurs, dans la version actuelle de PLT, le flag `gpus` ne [fait plus partie de l'API du Trainer](https://lightning.ai/docs/pytorch/stable/common/trainer.html#trainer-class-api) et ce n'est pas clair si les mainteneur ont laissé la possibilité d'utiliser le flag `gpus`, donc il est possible qu'une mise à jour oblige à passer à la nouvelle API.

**Comment by CharlesGaydon** [comment]
Corrigé par https://github.com/IGNF/myria3d/pull/105
